import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ErrorCode,
  McpError,
} from "@modelcontextprotocol/sdk/types.js";
import {
  ExperimentConfigSchema,
  StimulusGeneratorSchema,
  ParadigmSchema,
  AdaptiveConfigSchema,
} from "../../shared/schema.js";
import { z } from "zod";

class PsychoacousticServer {
  private server: Server;

  constructor() {
    this.server = new Server(
      {
        name: "psychoacoustic-expert",
        version: "1.0.0",
      },
      {
        capabilities: {
          tools: {},
        },
      }
    );

    this.setupTools();
    
    this.server.onerror = (error) => console.error("[MCP Error]", error);
    process.on("SIGINT", async () => {
      await this.server.close();
      process.exit(0);
    });
  }

  private setupTools() {
    this.server.setRequestHandler(ListToolsRequestSchema, async () => ({
      tools: [
        {
          name: "configure_stimulus",
          description: "Configure the basic stimulus (tone or harmonic complex) for the experiment.",
          inputSchema: {
            type: "object",
            properties: {
              type: { type: "string", enum: ["tone", "harmonic_complex"] },
              f0: { type: "number", description: "Fundamental frequency in Hz" },
              harmonics: {
                type: "object",
                properties: {
                  from: { type: "number" },
                  to: { type: "number" }
                }
              },
              duration: { type: "number", description: "Duration in ms" },
              levelDb: { type: "number", description: "Level in dB SPL" }
            },
            required: ["type", "duration", "levelDb"]
          }
        },
        {
          name: "configure_experiment",
          description: "Add paradigm, adaptive logic, and perturbations to a stimulus configuration.",
          inputSchema: {
            type: "object",
            properties: {
              stimulus: { type: "object" },
              paradigmType: { type: "string", enum: ["2AFC", "3AFC", "Probe-Signal"] },
              targetPerturbation: { type: "string", enum: ["spectral_profile", "onset_asynchrony", "mistuning"] },
              adaptiveParam: { type: "string" }
            },
            required: ["stimulus", "paradigmType", "targetPerturbation"]
          }
        },
        {
          name: "validate_experiment",
          description: "Validate an ExperimentConfig for acoustic safety and logical consistency.",
          inputSchema: {
            type: "object",
            properties: {
              config: { type: "object" }
            },
            required: ["config"]
          }
        }
      ],
    }));

    this.server.setRequestHandler(CallToolRequestSchema, async (request) => {
      switch (request.params.name) {
        case "configure_stimulus":
          return this.handleConfigureStimulus(request.params.arguments);
        case "configure_experiment":
          return this.handleConfigureExperiment(request.params.arguments);
        case "validate_experiment":
          return this.handleValidateExperiment(request.params.arguments);
        default:
          throw new McpError(
            ErrorCode.MethodNotFound,
            `Unknown tool: ${request.params.name}`
          );
      }
    });
  }

  private handleConfigureStimulus(args: any) {
    try {
      // Logic for stimulus configuration
      // We'll apply "Expert" defaults here
      const stimulus = {
        ...args,
        envelope: args.envelope || { attack: 10, release: 10 },
        phase: args.phase || "random"
      };

      if (args.type === "harmonic_complex" && !args.harmonics) {
        stimulus.harmonics = { from: 1, to: 20 };
      }

      return {
        content: [{ type: "text", text: JSON.stringify(stimulus, null, 2) }]
      };
    } catch (error: any) {
      return {
        isError: true,
        content: [{ type: "text", text: error.message }]
      };
    }
  }

  private handleConfigureExperiment(args: any) {
    // Logic for experiment configuration
    // Apply adaptive rules (2-down, 1-up default)
    const config = {
      meta: {
        name: "New Experiment",
        version: "1.0.0",
        seed: Math.floor(Math.random() * 1000000),
        rationale: "Generated by Expert Psychoacoustician."
      },
      audio: { sampleRate: 44100 },
      stimulus: args.stimulus,
      paradigm: {
        type: args.paradigmType,
        intervals: args.paradigmType === "2AFC" 
          ? [{ condition: "reference" }, { condition: "target" }]
          : [{ condition: "reference" }, { condition: "reference" }, { condition: "target" }],
        randomizeOrder: true,
        timing: { isi: 500 }
      },
      adaptive: {
        type: "staircase",
        parameter: args.adaptiveParam || "perturbations[0].deltaDb",
        initialValue: 10,
        stepSizes: [4, 2, 1],
        rule: { correctDown: 2, incorrectUp: 1 },
        initialN: 1,
        switchReversalCount: 2,
        minValue: 0,
        maxValue: 40,
        reversals: 12
      },
      termination: { reversals: 12 }
    };

    return {
      content: [{ type: "text", text: JSON.stringify(config, null, 2) }]
    };
  }

  private handleValidateExperiment(args: any) {
    const result = ExperimentConfigSchema.safeParse(args.config);
    if (!result.success) {
      return {
        isError: true,
        content: [{ type: "text", text: JSON.stringify(result.error.format(), null, 2) }]
      };
    }
    
    const config = result.data;
    const warnings: string[] = [];

    // Expert validation: Clipping check
    if (config.stimulus.type === "harmonic_complex") {
      const numHarmonics = config.stimulus.harmonics.to - config.stimulus.harmonics.from + 1;
      const levelDb = config.stimulus.amplitudeProfile.levelDb;
      // Very rough estimate: peak can be high if phases align
      if (levelDb + 20 * Math.log10(numHarmonics) > 90) {
        warnings.push("High risk of digital clipping! Sum of harmonics may exceed 0 dBFS. Consider lower levelDb or random phases.");
      }
    }

    return {
      content: [
        { 
          type: "text", 
          text: warnings.length > 0 
            ? `Validation Failed/Warnings:\n${warnings.join("\n")}` 
            : "Configuration is valid and acoustically safe." 
        }
      ]
    };
  }

  async run() {
    const transport = new StdioServerTransport();
    await this.server.connect(transport);
    console.error("Psychoacoustic MCP Server running on stdio");
  }
}

const server = new PsychoacousticServer();
server.run();
