import pandas as pd
import numpy as np
from scipy.optimize import curve_fit
import json

def parse_psychoacoustic_csv(uploaded_file):
    """
    Parses the CSV file generated by the Psychoacoustic Lab web app.
    Skips the header comments and loads the data.
    """
    # Read lines to find where the actual CSV header starts
    lines = uploaded_file.getvalue().decode('utf-8').splitlines()
    header_idx = 0
    for i, line in enumerate(lines):
        if line.startswith('trial,parameter_value'):
            header_idx = i
            break
    
    # Reset file pointer and read
    uploaded_file.seek(0)
    df = pd.read_csv(uploaded_file, skiprows=header_idx)
    
    # Parse the JSON column if it exists
    if 'resolved_stimulus_state_json' in df.columns:
        df['stimulus_state'] = df['resolved_stimulus_state_json'].apply(
            lambda x: json.loads(x) if pd.notna(x) else None
        )
        
    return df

def parse_psychoacoustic_json(uploaded_file):
    """
    Parses the JSON file generated by the Psychoacoustic Lab web app.
    Returns a DataFrame with the history.
    """
    # Ensure we start from the beginning of the file
    if hasattr(uploaded_file, 'seek'):
        uploaded_file.seek(0)
    
    data = json.load(uploaded_file)
    history = data.get('history', [])
    
    if not history:
        return pd.DataFrame()
    
    # Convert history list of dicts to DataFrame
    df = pd.DataFrame(history)
    
    # Unpack the 'metadata' column if it exists (contains targetInterval, response, trialState)
    if 'metadata' in df.columns:
        # Use json_normalize to flatten the metadata dicts into separate columns
        # We handle cases where some trials might be missing metadata
        meta_df = pd.json_normalize(df['metadata'].tolist())
        # Rename columns to match what the analysis scripts expect (from CSV version)
        if 'targetInterval' in meta_df.columns:
            meta_df['target_interval'] = meta_df['targetInterval']
        if 'response' in meta_df.columns:
            meta_df['response_interval'] = meta_df['response']
        
        # Merge back with the main dataframe
        df = pd.concat([df.drop(columns=['metadata']), meta_df], axis=1)
    
    # The JSON history might have trialIndex (0-based) while CSV had trial (1-based)
    if 'trialIndex' in df.columns:
        df['trial'] = df['trialIndex'] + 1
    
    # The JSON has parameter value in 'value'
    if 'value' in df.columns:
        df['parameter_value'] = df['value']
        
    # The JSON has correct as 'correct' (already boolean)
    # Reversal as 'isReversal'
    if 'isReversal' in df.columns:
        df['is_reversal'] = df['isReversal']
        
    return df

# --- Psychometric Functions ---
# We fit P(correct) as a function of the stimulus intensity (x)
# For 2AFC, gamma (guess rate) is 0.5. lambda (lapse rate) is often fixed or constrained.

def logistic_function(x, alpha, beta, lapse=0.02):
    """
    Logistic function for 2AFC.
    alpha: threshold (point of subjective equality)
    beta: slope
    lapse: lapse rate (upper asymptote = 1 - lapse)
    """
    gamma = 0.5
    return gamma + (1 - gamma - lapse) * (1 / (1 + np.exp(-beta * (x - alpha))))

def weibull_function(x, alpha, beta, lapse=0.02):
    """
    Weibull function for 2AFC. Often used when x is strictly positive (like Delta dB).
    alpha: threshold
    beta: slope
    """
    gamma = 0.5
    # To prevent log(negative), return gamma if x < 0 (though x should be > 0 for Weibull)
    x = np.maximum(x, 1e-9)
    return gamma + (1 - gamma - lapse) * (1 - np.exp(- (x / alpha)**beta))

def fit_psychometric_curve(x_data, y_data, func_type="Logistic"):
    """
    Fits the psychometric curve using Maximum Likelihood / Least Squares.
    Returns the fitted parameters and a function for plotting.
    """
    # Group data by parameter value to get proportions
    df = pd.DataFrame({'x': x_data, 'correct': y_data})
    grouped = df.groupby('x').agg(
        p_correct=('correct', 'mean'),
        n_trials=('correct', 'count')
    ).reset_index()

    # Initial guesses:
    # alpha: median of x
    # beta: 1.0
    p0 = [np.median(x_data), 1.0]
    
    func = logistic_function if func_type == "Logistic" else weibull_function

    try:
        # Use curve_fit (non-linear least squares) weighted by number of trials
        popt, pcov = curve_fit(
            lambda x, a, b: func(x, a, b), 
            grouped['x'], 
            grouped['p_correct'], 
            p0=p0,
            sigma=1/np.sqrt(grouped['n_trials']),
            bounds=([0.001, 0.01], [np.max(x_data)*2, 50])
        )
        return popt, grouped
    except Exception as e:
        return None, grouped

def calculate_threshold(alpha, beta, target_p=0.794, func_type="Logistic", lapse=0.02):
    """
    Inverse of the psychometric function to find the exact threshold.
    0.794 corresponds to the 3-down 1-up rule.
    0.707 corresponds to the 2-down 1-up rule.
    """
    gamma = 0.5
    # normalized p target
    p_norm = (target_p - gamma) / (1 - gamma - lapse)
    
    if p_norm >= 1 or p_norm <= 0:
        return None # Target P is unreachable given the lapse rate
        
    if func_type == "Logistic":
        # p = 1 / (1 + exp(-beta*(x-alpha)))
        # 1/p - 1 = exp(-beta*(x-alpha))
        # -ln(1/p - 1)/beta + alpha = x
        return alpha - np.log(1/p_norm - 1) / beta
    elif func_type == "Weibull":
        # p = 1 - exp(-(x/alpha)**beta)
        # 1-p = exp(-(x/alpha)**beta)
        # -ln(1-p) = (x/alpha)**beta
        # alpha * (-ln(1-p))**(1/beta) = x
        return alpha * (-np.log(1 - p_norm))**(1/beta)
    return None
